# Shell Constants
BIF_RETURNONLYFSDIRS = 0x0001
BIF_DONTGOBELOWDOMAIN = 0x0002
BIF_STATUSTEXT = 0x0004
BIF_RETURNFSANCESTORS = 0x0008
BIF_EDITBOX = 0x0010
BIF_VALIDATE = 0x0020
BIF_NEWDIALOGSTYLE = 0x0040
BIF_BROWSEINCLUDEURLS = 0x0080
BIF_UAHINT = 0x0100
BIF_NONEWFOLDERBUTTON = 0x0200
BIF_NOTRANSLATETARGETS = 0x0400
BIF_BROWSEFORCOMPUTER = 0x1000
BIF_BROWSEFORPRINTER = 0x2000
BIF_BROWSEINCLUDEFILES = 0x4000
BIF_SHAREABLE = 0x8000

# Shell Special Folder Constants
SSF_DESKTOP = 0
SSF_DRIVES = 17 # My Computer

# Copy Flags
FOF_SILENT = 4
FOF_NOCONFIRMATION = 16
FOF_NOERRORUI = 1024
COPY_FLAGS_SILENT = FOF_SILENT | FOF_NOCONFIRMATION | FOF_NOERRORUI

# Copy Configuration
CHUNK_SIZE = 1024 * 1024 # 1MB
MAX_RETRIES = 3
VERIFY_TIMEOUT = 120
RETRY_DELAY = 1
VERIFY_POLL_INTERVAL = 0.2

# Allowed Extensions
ALLOWED_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.heic', '.mov', '.mp4', '.avi', '.m4v'}

# UI Configuration
APP_VERSION = "1.0.0"
WINDOW_TITLE = f"CiderBridge v{APP_VERSION}"
WINDOW_GEOMETRY = "700x850"
THEME_MODE = "Dark"
THEME_COLOR = "dark-blue"

# Colors
COLOR_WARNING_BG = "#330000"
COLOR_WARNING_TEXT = "#FF4444"
COLOR_INSTRUCTION_BG = "#FF9500" # Orange
COLOR_INSTRUCTION_TEXT = "black"
COLOR_BUTTON_MTP = "#E0A800"
COLOR_BUTTON_MTP_HOVER = "#B08800"
COLOR_TEXT_GRAY = "#AAAAAA"
COLOR_TEXT_WHITE = "white"

# Fonts
FONT_HEADER_LARGE = ("Segoe UI", 26, "bold")
FONT_HEADER_MEDIUM = ("Segoe UI", 16, "bold")
FONT_WARNING = ("Segoe UI", 14, "bold")
FONT_INSTRUCTION = ("Segoe UI", 12, "bold")
FONT_BUTTON = ("Segoe UI", 14, "bold")
FONT_NORMAL = ("Segoe UI", 13)

# Timing
QUEUE_CHECK_INTERVAL_MS = 100
TIMER_UPDATE_INTERVAL_MS = 1000
